"""Catálogo maestro de fuentes. Es la semilla del `source_registry` (SQLite).

`kind` distingue la naturaleza del dato y la interfaz lo muestra siempre:
  oficial       dato publicado por una institución pública
  vivo_tercero  dato en vivo de un tercero (ADS-B comunitario, AIS, TomTom, NASA FIRMS)
  calculado     dato derivado aquí con una fórmula reproducible (tasas, cambios, índice)
  estimacion    estimación estadística (p. ej. población proyectada)
  proyeccion    pronóstico (modelo meteorológico o estadístico)
  ia            interpretación generada por un modelo de lenguaje
"""
from __future__ import annotations

PORTAL = "https://www.datosabiertos.gob.pe"
FILES = f"{PORTAL}/sites/default/files"

SOURCES: list[dict] = [
    # ── Seguridad y criminalidad ───────────────────────────────────────────
    {
        "source_id": "mininter_sidpol",
        "name": "Denuncias policiales registradas a nivel nacional (SIDPOL)",
        "institution": "Ministerio del Interior · DIRTIC-PNP",
        "url": f"{PORTAL}/dataset/denuncias-policiales-registradas-nivel-nacional-mininter",
        "download": f"{FILES}/DATASET_Denuncias_Policiales_Ene%202018%20a%20Julio%202026.csv",
        "adapter": "peru_intel.ingestion.mininter_sidpol",
        "official": 1, "kind": "oficial", "type": "csv",
        "license": "Datos abiertos del Estado peruano (PNDA)",
        "update_frequency": "mensual", "geographic_level": "distrito (UBIGEO del hecho)",
        "coverage_start": "2018-01",
        "notes": "Solo publica las principales modalidades (robo, hurto, estafa, extorsión, secuestro, violencia contra la mujer y «otros»).",
    },
    {
        "source_id": "mininter_indicadores",
        "name": "Indicadores para planes de acción de seguridad ciudadana",
        "institution": "Ministerio del Interior · Observatorio Nacional de Seguridad Ciudadana",
        "url": f"{PORTAL}/dataset/indicadores-de-seguridad-ciudadana-y-tendencias-territoriales-mininter",
        "download": f"{FILES}/DataSet_Ind_Plan_Acc_Segu_Ciud_Jul%202026.zip",
        "dictionary": f"{FILES}/DICCIONAR_DATOS_%20Ind_%20Plan_Acc_Seg_Ciud_Jun%202026.xlsx",
        "adapter": "peru_intel.ingestion.mininter_indicators",
        "official": 1, "kind": "oficial", "type": "zip/csv",
        "license": "Datos abiertos del Estado peruano (PNDA)",
        "update_frequency": "mensual", "geographic_level": "región, provincia y distrito",
        "coverage_start": "2009",
        "notes": "Combina SIDPOL, ENAPRES (victimización), CEIC (homicidios), DEVIDA, SISEVE, RENAMU y otras fuentes.",
    },
    {
        "source_id": "mininter_tendencias",
        "name": "Tendencias para planes de acción de seguridad ciudadana",
        "institution": "Ministerio del Interior · Observatorio Nacional de Seguridad Ciudadana",
        "url": f"{PORTAL}/dataset/indicadores-de-seguridad-ciudadana-y-tendencias-territoriales-mininter",
        "download": f"{FILES}/DataSet_Ten_Plan_Acc_Segu_Ciud_%20Jul%202026.zip",
        "adapter": "peru_intel.ingestion.mininter_indicators",
        "official": 1, "kind": "oficial", "type": "zip/csv",
        "license": "Datos abiertos del Estado peruano (PNDA)",
        "update_frequency": "mensual", "geographic_level": "región, provincia y distrito",
    },
    {
        "source_id": "inei_poblacion",
        "name": "Población proyectada por UBIGEO y año",
        "institution": "INEI (proyecciones) · publicada en el dataset de indicadores MININTER",
        "url": f"{PORTAL}/dataset/indicadores-de-seguridad-ciudadana-y-tendencias-territoriales-mininter",
        "adapter": "peru_intel.ingestion.inei_population",
        "official": 1, "kind": "estimacion", "type": "derivado",
        "license": "Datos abiertos del Estado peruano (PNDA)",
        "update_frequency": "anual", "geographic_level": "región, provincia y distrito",
        "coverage_start": "2009",
        "notes": "Columna POBLACION_PROYECTADA del dataset MININTER. Es una proyección, no un conteo censal. "
                 "Se puede reemplazar por un archivo INEI directo en data/raw/inei/ (ver DOCUMENTACION.md).",
    },
    {
        "source_id": "mpfn_delitos",
        "name": "[MPFN] Delitos denunciados",
        "institution": "Ministerio Público – Fiscalía de la Nación · Observatorio de Criminalidad",
        "url": f"{PORTAL}/dataset/mpfn-delitos-denunciados",
        "adapter": "peru_intel.ingestion.mpfn",
        "official": 1, "kind": "oficial", "type": "csv",
        "license": "Datos abiertos del Estado peruano (PNDA)",
        "update_frequency": "anual / semestral", "geographic_level": "distrito fiscal (sede con UBIGEO)",
        "coverage_start": "2020",
        "notes": "Granularidad por distrito fiscal; en el mapa se agrega al departamento de la sede.",
    },
    {
        "source_id": "devida",
        "name": "Cultivos de coca, erradicación y decomisos por departamento",
        "institution": "DEVIDA",
        "url": f"{PORTAL}/group/comisi%C3%B3n-nacional-para-el-desarrollo-y-vida-sin-drogas-devida",
        "adapter": "peru_intel.ingestion.devida",
        "official": 1, "kind": "oficial", "type": "xlsx",
        "license": "Datos abiertos del Estado peruano (PNDA)",
        "update_frequency": "anual", "geographic_level": "departamento",
        "coverage_start": "2018",
    },
    # ── Territorio ─────────────────────────────────────────────────────────
    {
        "source_id": "limites_inei",
        "name": "Límites departamentales, provinciales y distritales (simplificados)",
        "institution": "INEI (cartografía base) vía paquete OCE/FEDTID",
        "url": "https://www.inei.gob.pe/",
        "adapter": "peru_intel.map.territory",
        "official": 1, "kind": "oficial", "type": "geojson",
        "license": "Datos públicos del Estado peruano",
        "update_frequency": "eventual", "geographic_level": "departamento, provincia, distrito",
        "notes": "Polígonos provinciales generados aquí disolviendo distritos por UBIGEO (DuckDB spatial).",
    },
    {
        "source_id": "openfreemap",
        "name": "Mapa base vectorial OpenFreeMap (OpenStreetMap)",
        "institution": "OpenFreeMap · contribuidores de OpenStreetMap",
        "url": "https://openfreemap.org/",
        "adapter": "peru_intel.map.ofm_proxy",
        "official": 0, "kind": "vivo_tercero", "type": "tiles",
        "license": "ODbL (datos OSM) · estilos OpenMapTiles", "update_frequency": "semanal",
        "geographic_level": "calle",
    },
    # ── Infraestructura ────────────────────────────────────────────────────
    {
        "source_id": "apn_wpi_puertos",
        "name": "Puertos del Perú: carga (APN) + World Port Index (NGA)",
        "institution": "Autoridad Portuaria Nacional · NGA (EE. UU.)",
        "url": "https://piep.apn.gob.pe/datos-portuarios/",
        "adapter": "peru_intel.ingestion.ports",
        "official": 1, "kind": "oficial", "type": "xlsx/csv",
        "license": "Datos públicos", "update_frequency": "anual", "geographic_level": "puerto",
        "notes": "Pipeline build-international-data.mjs de OCE/FEDTID.",
    },
    {
        "source_id": "osm_datacenters",
        "name": "Centros de datos (telecom=data_center)",
        "institution": "OpenStreetMap vía RUC360",
        "url": "https://www.openstreetmap.org/",
        "adapter": "peru_intel.ingestion.ports",
        "official": 0, "kind": "vivo_tercero", "type": "json",
        "license": "ODbL", "update_frequency": "eventual", "geographic_level": "punto",
    },
    # ── En vivo ────────────────────────────────────────────────────────────
    {
        "source_id": "adsb_lol",
        "name": "Aeronaves ADS-B en vivo",
        "institution": "adsb.lol (red comunitaria) + adsbdb.com",
        "url": "https://api.adsb.lol/",
        "adapter": "peru_intel.live.adsb",
        "official": 0, "kind": "vivo_tercero", "type": "api",
        "license": "ODbL (adsb.lol)", "update_frequency": "~15 s", "geographic_level": "punto",
    },
    {
        "source_id": "aisstream",
        "name": "Embarcaciones AIS en vivo",
        "institution": "aisstream.io",
        "url": "https://aisstream.io/",
        "adapter": "peru_intel.live.ais",
        "official": 0, "kind": "vivo_tercero", "type": "websocket",
        "license": "Términos de aisstream.io", "update_frequency": "continuo", "geographic_level": "punto",
        "requires_key": "aisstream_key",
    },
    {
        "source_id": "celestrak",
        "name": "Elementos orbitales (GP/TLE)",
        "institution": "CelesTrak",
        "url": "https://celestrak.org/NORAD/elements/",
        "adapter": "peru_intel.live.celestrak",
        "official": 0, "kind": "vivo_tercero", "type": "api",
        "license": "Uso público con atribución", "update_frequency": "6 h", "geographic_level": "órbita",
    },
    {
        "source_id": "tomtom_traffic",
        "name": "Tráfico en vivo (flujo relativo)",
        "institution": "TomTom",
        "url": "https://developer.tomtom.com/traffic-api",
        "adapter": "peru_intel.live.traffic",
        "official": 0, "kind": "vivo_tercero", "type": "tiles/api",
        "license": "Términos comerciales TomTom (BYOK)", "update_frequency": "~1 min", "geographic_level": "tramo vial",
        "requires_key": "tomtom_key",
    },
    {
        "source_id": "igp_sismos",
        "name": "Sismos reportados",
        "institution": "Instituto Geofísico del Perú · CENSIS",
        "url": "https://ultimosismo.igp.gob.pe/",
        "adapter": "peru_intel.live.seismic",
        "official": 1, "kind": "oficial", "type": "api",
        "license": "Datos públicos IGP", "update_frequency": "minutos", "geographic_level": "epicentro",
    },
    {
        "source_id": "usgs_sismos",
        "name": "Sismos (fuente global secundaria)",
        "institution": "USGS Earthquake Hazards Program",
        "url": "https://earthquake.usgs.gov/earthquakes/feed/",
        "adapter": "peru_intel.live.seismic",
        "official": 1, "kind": "oficial", "type": "api",
        "license": "Dominio público (EE. UU.)", "update_frequency": "minutos", "geographic_level": "epicentro",
    },
    {
        "source_id": "nasa_firms",
        "name": "Focos de calor satelitales (VIIRS)",
        "institution": "NASA FIRMS",
        "url": "https://firms.modaps.eosdis.nasa.gov/",
        "adapter": "peru_intel.live.firms",
        "official": 1, "kind": "vivo_tercero", "type": "api",
        "license": "Datos abiertos NASA (MAP_KEY gratuita)", "update_frequency": "~3 h", "geographic_level": "píxel 375 m",
        "requires_key": "firms_key",
        "notes": "Un foco de calor satelital no es un incendio confirmado.",
    },
    {
        "source_id": "senamhi_estaciones",
        "name": "Observaciones de estaciones automáticas",
        "institution": "SENAMHI",
        "url": "https://www.senamhi.gob.pe/",
        "adapter": "peru_intel.live.weather",
        "official": 1, "kind": "oficial", "type": "csv",
        "license": "Datos públicos SENAMHI", "update_frequency": "horaria", "geographic_level": "estación",
        "requires_key": "senamhi_csv_url",
        "notes": "Requiere configurar la URL o el archivo del dataset de estaciones (ver DOCUMENTACION.md).",
    },
    {
        "source_id": "modelo_gfs",
        "name": "Pronóstico NOAA GFS (vía Open-Meteo)",
        "institution": "NOAA · servido por Open-Meteo",
        "url": "https://open-meteo.com/en/docs/gfs-api",
        "adapter": "peru_intel.live.weather",
        "official": 0, "kind": "proyeccion", "type": "api",
        "license": "CC BY 4.0 (Open-Meteo)", "update_frequency": "1 h", "geographic_level": "punto (capital departamental)",
    },
    {
        "source_id": "modelo_ecmwf",
        "name": "Pronóstico ECMWF IFS (vía Open-Meteo)",
        "institution": "ECMWF · servido por Open-Meteo",
        "url": "https://open-meteo.com/en/docs/ecmwf-api",
        "adapter": "peru_intel.live.weather",
        "official": 0, "kind": "proyeccion", "type": "api",
        "license": "CC BY 4.0 (Open-Meteo)", "update_frequency": "1 h", "geographic_level": "punto (capital departamental)",
    },
    # ── Clima combinado (proveedores por punto y capas) ────────────────────
    {"source_id": "openmeteo", "name": "Condiciones actuales y pronóstico por punto (Open-Meteo)", "institution": "Open-Meteo",
     "url": "https://open-meteo.com/en/docs", "adapter": "peru_intel.weather.providers", "official": 0, "kind": "proyeccion",
     "type": "api", "license": "CC BY 4.0 · gratuito para uso no comercial (10 000 llamadas/día)", "update_frequency": "15 min – 1 h",
     "geographic_level": "punto (mundo)", "notes": "Proveedor principal. Valores de modelo, no observaciones."},
    {"source_id": "metno", "name": "Locationforecast 2.0", "institution": "MET Norway (Instituto Meteorológico de Noruega)",
     "url": "https://api.met.no/", "adapter": "peru_intel.weather.providers", "official": 1, "kind": "proyeccion", "type": "api",
     "license": "CC BY 4.0 / NLOD · exige User-Agent identificable", "update_frequency": "1 h", "geographic_level": "punto (mundo)"},
    {"source_id": "weatherapi", "name": "Tiempo real (WeatherAPI.com)", "institution": "WeatherAPI.com", "url": "https://www.weatherapi.com/",
     "adapter": "peru_intel.weather.providers", "official": 0, "kind": "vivo_tercero", "type": "api",
     "license": "Plan gratuito 100 000 llamadas/mes (términos del proveedor)", "update_frequency": "15 min",
     "geographic_level": "punto (mundo)", "requires_key": "weatherapi_key"},
    {"source_id": "visualcrossing", "name": "Timeline (Visual Crossing)", "institution": "Visual Crossing",
     "url": "https://www.visualcrossing.com/weather-api/", "adapter": "peru_intel.weather.providers", "official": 0,
     "kind": "vivo_tercero", "type": "api", "license": "Plan gratuito 1 000 registros/día (términos del proveedor)",
     "update_frequency": "1 h", "geographic_level": "punto (mundo)", "requires_key": "visualcrossing_key"},
    {"source_id": "openweather", "name": "Current Weather 2.5 (OpenWeather)", "institution": "OpenWeather",
     "url": "https://openweathermap.org/api", "adapter": "peru_intel.weather.providers", "official": 0, "kind": "vivo_tercero",
     "type": "api", "license": "Plan gratuito 1 000 llamadas/día (términos del proveedor)", "update_frequency": "10 min",
     "geographic_level": "punto (mundo)", "requires_key": "openweather_key"},
    {"source_id": "tomorrowio", "name": "Realtime (Tomorrow.io)", "institution": "Tomorrow.io", "url": "https://www.tomorrow.io/weather-api/",
     "adapter": "peru_intel.weather.providers", "official": 0, "kind": "vivo_tercero", "type": "api",
     "license": "Plan gratuito (términos del proveedor)", "update_frequency": "1 min – 1 h", "geographic_level": "punto (mundo)",
     "requires_key": "tomorrow_key"},
    {"source_id": "nasa_gibs", "name": "Capas satelitales casi en tiempo real (GIBS WMTS)", "institution": "NASA EOSDIS",
     "url": "https://nasa-gibs.github.io/gibs-api-docs/", "adapter": "peru_intel.weather.overlays", "official": 1,
     "kind": "vivo_tercero", "type": "tiles", "license": "Datos abiertos NASA (atribución)", "update_frequency": "diaria (NRT ~3 h)",
     "geographic_level": "píxel (mundo)"},
    {"source_id": "senamhi_idesep", "name": "Geoservicios WMS del IDESEP (avisos, pronóstico, monitoreo, climatología)",
     "institution": "SENAMHI", "url": "https://idesep.senamhi.gob.pe/portalidesep/wms.do", "adapter": "peru_intel.weather.overlays",
     "official": 1, "kind": "oficial", "type": "wms", "license": "Datos públicos SENAMHI",
     "update_frequency": "según producto (horas a meses)", "geographic_level": "ráster / polígono (Perú)"},
    # ── Mapas base realistas y relieve ─────────────────────────────────────
    {"source_id": "esri_imagery", "name": "World Imagery (satélite y aérea)", "institution": "Esri, Maxar, Earthstar Geographics",
     "url": "https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9", "adapter": "peru_intel.map.basemaps",
     "official": 0, "kind": "vivo_tercero", "type": "tiles", "license": "Términos de uso de Esri", "update_frequency": "variable por zona",
     "geographic_level": "hasta ~30 cm"},
    {"source_id": "eox_sentinel", "name": "Sentinel-2 cloudless 2024", "institution": "EOX IT Services · Copernicus",
     "url": "https://s2maps.eu/", "adapter": "peru_intel.map.basemaps", "official": 0, "kind": "vivo_tercero", "type": "tiles",
     "license": "CC BY-NC-SA 4.0 (no comercial)", "update_frequency": "anual", "geographic_level": "10 m"},
    {"source_id": "opentopomap", "name": "OpenTopoMap", "institution": "OpenTopoMap · OSM", "url": "https://opentopomap.org/",
     "adapter": "peru_intel.map.basemaps", "official": 0, "kind": "vivo_tercero", "type": "tiles", "license": "CC BY-SA",
     "update_frequency": "eventual", "geographic_level": "calle"},
    {"source_id": "terrain_tiles", "name": "Terrain Tiles (Terrarium) para relieve 3D", "institution": "Mapzen · AWS Open Data",
     "url": "https://registry.opendata.aws/terrain-tiles/", "adapter": "peru_intel.map.basemaps", "official": 0,
     "kind": "vivo_tercero", "type": "tiles", "license": "Atribución por fuente (SRTM, GMTED, ETOPO1)",
     "update_frequency": "estática", "geographic_level": "~30–90 m"},
    {"source_id": "ign_carta", "name": "Carta Nacional 1:100 000", "institution": "Instituto Geográfico Nacional del Perú",
     "url": "https://portalgeo.idep.gob.pe/", "adapter": "peru_intel.map.basemaps", "official": 1, "kind": "oficial", "type": "tiles",
     "license": "Datos públicos IGN", "update_frequency": "eventual", "geographic_level": "1:100 000"},
    # ── Instituciones de seguridad y justicia (ubicación aproximada) ──────
    {"source_id": "osm_instituciones", "name": "Comisarías, serenazgo, fiscalías y juzgados (ubicación aproximada)",
     "institution": "OpenStreetMap (Overpass API)", "url": "https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpolice",
     "adapter": "peru_intel.ingestion.institutions", "official": 0, "kind": "vivo_tercero", "type": "api",
     "license": "ODbL", "update_frequency": "a demanda (ingest instituciones --download)", "geographic_level": "punto",
     "notes": "Cartografía colaborativa: la ubicación es aproximada y puede faltar o sobrar alguna sede. No existe un "
              "dataset abierto oficial con coordenadas de todas las sedes PNP, serenazgo, Ministerio Público y Poder Judicial."},
    # ── El Niño y océano ───────────────────────────────────────────────────
    {"source_id": "igp_icen", "name": "Índice Costero El Niño (ICEN) mensual", "institution": "IGP · ENFEN",
     "url": "http://met.igp.gob.pe/variabclim/indices.html", "adapter": "peru_intel.climate.enso", "official": 1,
     "kind": "oficial", "type": "txt", "license": "Datos públicos del Estado peruano", "update_frequency": "mensual",
     "geographic_level": "región Niño 1+2", "coverage_start": "1950-01",
     "notes": "Media móvil de 3 meses de la anomalía de TSM en Niño 1+2 (ERSSTv5). Define magnitud y fechas de los eventos."},
    {"source_id": "igp_eventos", "name": "Eventos El Niño y La Niña costeros (ICEN, ENFEN 2024)", "institution": "IGP · ENFEN",
     "url": "http://met.igp.gob.pe/datos/lista_eventos_ICEN.html", "adapter": "peru_intel.climate.enso", "official": 1,
     "kind": "oficial", "type": "html", "license": "Datos públicos del Estado peruano", "update_frequency": "al cerrar cada evento",
     "geographic_level": "región Niño 1+2", "coverage_start": "1950"},
    {"source_id": "noaa_cpc_mensual", "name": "TSM y anomalía mensual por región Niño (OISST)", "institution": "NOAA Climate Prediction Center",
     "url": "https://www.cpc.ncep.noaa.gov/data/indices/", "adapter": "peru_intel.climate.enso", "official": 1, "kind": "oficial",
     "type": "txt", "license": "Dominio público (EE. UU.)", "update_frequency": "mensual", "geographic_level": "regiones Niño",
     "coverage_start": "1982-01"},
    {"source_id": "noaa_cpc_semanal", "name": "TSM y anomalía semanal por región Niño", "institution": "NOAA Climate Prediction Center",
     "url": "https://www.cpc.ncep.noaa.gov/data/indices/wksst9120.for", "adapter": "peru_intel.climate.enso", "official": 1,
     "kind": "oficial", "type": "txt", "license": "Dominio público (EE. UU.)", "update_frequency": "semanal",
     "geographic_level": "regiones Niño", "notes": "Climatología base 1991–2020."},
    {"source_id": "enfen_comunicados", "name": "Comunicados oficiales y estado del sistema de alerta", "institution": "ENFEN (Comisión Multisectorial)",
     "url": "https://enfen.imarpe.gob.pe/comunicados/", "adapter": "config/enso_eventos.json (curado)", "official": 1, "kind": "oficial",
     "type": "pdf", "license": "Datos públicos del Estado peruano", "update_frequency": "quincenal", "geographic_level": "nacional",
     "notes": "Se transcribe a mano el comunicado vigente con su enlace; revisar cada quincena (próximo: 15 oct 2026)."},
    {"source_id": "openmeteo_marine", "name": "Corrientes superficiales y TSM (Marine API)", "institution": "Open-Meteo (modelos MeteoFrance/ECMWF)",
     "url": "https://open-meteo.com/en/docs/marine-weather-api", "adapter": "peru_intel.climate.enso", "official": 0,
     "kind": "proyeccion", "type": "api", "license": "CC BY 4.0 · uso no comercial gratuito", "update_frequency": "3 h",
     "geographic_level": "rejilla 1,5°", "notes": "Valores de modelo oceánico, no boyas."},
    {"source_id": "airplanes_live", "name": "Aeronaves ADS-B en vivo (red comunitaria)", "institution": "airplanes.live",
     "url": "https://airplanes.live/api-guide/", "adapter": "peru_intel.live.adsb", "official": 0, "kind": "vivo_tercero",
     "type": "api", "license": "Uso no comercial (términos del proveedor)", "update_frequency": "~12 s", "geographic_level": "punto"},
    {"source_id": "adsb_fi", "name": "Aeronaves ADS-B en vivo (red comunitaria)", "institution": "adsb.fi",
     "url": "https://github.com/adsbfi/opendata", "adapter": "peru_intel.live.adsb", "official": 0, "kind": "vivo_tercero",
     "type": "api", "license": "Datos abiertos (uso personal / no comercial)", "update_frequency": "~12 s", "geographic_level": "punto"},
    {"source_id": "vision_edge", "name": "Cámaras propias (grabador Dahua / ONVIF / RTSP)", "institution": "Equipo propio del usuario",
     "url": "plugins/vision-edge/README.md", "adapter": "peru_intel.vision", "official": 0, "kind": "vivo_tercero", "type": "rtsp/cgi",
     "license": "Propio · Ley N.° 29733", "update_frequency": "en vivo", "geographic_level": "punto (canal)"},
    # ── Derivados internos ─────────────────────────────────────────────────
    {
        "source_id": "indice_situacional_v1",
        "name": "Índice Situacional Perú v1 (experimental, no oficial)",
        "institution": "Cálculo propio · config/crime_index_v1.yaml",
        "url": "config/crime_index_v1.yaml",
        "adapter": "peru_intel.analytics.index",
        "official": 0, "kind": "calculado", "type": "derivado",
        "license": "Interno", "update_frequency": "al recalcular", "geographic_level": "departamento",
        "notes": "No es un índice oficial del MININTER ni de ninguna institución.",
    },
]

BY_ID = {s["source_id"]: s for s in SOURCES}
