"""Catálogo maestro de fuentes. Es la semilla del `source_registry` (SQLite).

`kind` distingue la naturaleza del dato y la interfaz lo muestra siempre:
  oficial       dato publicado por una institución pública
  vivo_tercero  dato en vivo de un tercero (ADS-B comunitario, AIS, TomTom, NASA FIRMS)
  calculado     dato derivado aquí con una fórmula reproducible (tasas, cambios, índice)
  estimacion    estimación estadística (p. ej. población proyectada)
  proyeccion    pronóstico (modelo meteorológico o estadístico)
  ia            interpretación generada por un modelo de lenguaje
"""
from __future__ import annotations

PORTAL = "https://www.datosabiertos.gob.pe"
FILES = f"{PORTAL}/sites/default/files"

SOURCES: list[dict] = [
    # ── Seguridad y criminalidad ───────────────────────────────────────────
    {
        "source_id": "mininter_sidpol",
        "name": "Denuncias policiales registradas a nivel nacional (SIDPOL)",
        "institution": "Ministerio del Interior · DIRTIC-PNP",
        "url": f"{PORTAL}/dataset/denuncias-policiales-registradas-nivel-nacional-mininter",
        "download": f"{FILES}/DATASET_Denuncias_Policiales_Ene%202018%20a%20Julio%202026.csv",
        "adapter": "peru_intel.ingestion.mininter_sidpol",
        "official": 1, "kind": "oficial", "type": "csv",
        "license": "Datos abiertos del Estado peruano (PNDA)",
        "update_frequency": "mensual", "geographic_level": "distrito (UBIGEO del hecho)",
        "coverage_start": "2018-01",
        "notes": "Solo publica las principales modalidades (robo, hurto, estafa, extorsión, secuestro, violencia contra la mujer y «otros»).",
    },
    {
        "source_id": "mininter_indicadores",
        "name": "Indicadores para planes de acción de seguridad ciudadana",
        "institution": "Ministerio del Interior · Observatorio Nacional de Seguridad Ciudadana",
        "url": f"{PORTAL}/dataset/indicadores-de-seguridad-ciudadana-y-tendencias-territoriales-mininter",
        "download": f"{FILES}/DataSet_Ind_Plan_Acc_Segu_Ciud_Jul%202026.zip",
        "dictionary": f"{FILES}/DICCIONAR_DATOS_%20Ind_%20Plan_Acc_Seg_Ciud_Jun%202026.xlsx",
        "adapter": "peru_intel.ingestion.mininter_indicators",
        "official": 1, "kind": "oficial", "type": "zip/csv",
        "license": "Datos abiertos del Estado peruano (PNDA)",
        "update_frequency": "mensual", "geographic_level": "región, provincia y distrito",
        "coverage_start": "2009",
        "notes": "Combina SIDPOL, ENAPRES (victimización), CEIC (homicidios), DEVIDA, SISEVE, RENAMU y otras fuentes.",
    },
    {
        "source_id": "mininter_tendencias",
        "name": "Tendencias para planes de acción de seguridad ciudadana",
        "institution": "Ministerio del Interior · Observatorio Nacional de Seguridad Ciudadana",
        "url": f"{PORTAL}/dataset/indicadores-de-seguridad-ciudadana-y-tendencias-territoriales-mininter",
        "download": f"{FILES}/DataSet_Ten_Plan_Acc_Segu_Ciud_%20Jul%202026.zip",
        "adapter": "peru_intel.ingestion.mininter_indicators",
        "official": 1, "kind": "oficial", "type": "zip/csv",
        "license": "Datos abiertos del Estado peruano (PNDA)",
        "update_frequency": "mensual", "geographic_level": "región, provincia y distrito",
    },
    {
        "source_id": "inei_poblacion",
        "name": "Población proyectada por UBIGEO y año",
        "institution": "INEI (proyecciones) · publicada en el dataset de indicadores MININTER",
        "url": f"{PORTAL}/dataset/indicadores-de-seguridad-ciudadana-y-tendencias-territoriales-mininter",
        "adapter": "peru_intel.ingestion.inei_population",
        "official": 1, "kind": "estimacion", "type": "derivado",
        "license": "Datos abiertos del Estado peruano (PNDA)",
        "update_frequency": "anual", "geographic_level": "región, provincia y distrito",
        "coverage_start": "2009",
        "notes": "Columna POBLACION_PROYECTADA del dataset MININTER. Es una proyección, no un conteo censal. "
                 "Se puede reemplazar por un archivo INEI directo en data/raw/inei/ (ver DOCUMENTACION.md).",
    },
    {
        "source_id": "mpfn_delitos",
        "name": "[MPFN] Delitos denunciados",
        "institution": "Ministerio Público – Fiscalía de la Nación · Observatorio de Criminalidad",
        "url": f"{PORTAL}/dataset/mpfn-delitos-denunciados",
        "adapter": "peru_intel.ingestion.mpfn",
        "official": 1, "kind": "oficial", "type": "csv",
        "license": "Datos abiertos del Estado peruano (PNDA)",
        "update_frequency": "anual / semestral", "geographic_level": "distrito fiscal (sede con UBIGEO)",
        "coverage_start": "2020",
        "notes": "Granularidad por distrito fiscal; en el mapa se agrega al departamento de la sede.",
    },
    {
        "source_id": "devida",
        "name": "Cultivos de coca, erradicación y decomisos por departamento",
        "institution": "DEVIDA",
        "url": f"{PORTAL}/group/comisi%C3%B3n-nacional-para-el-desarrollo-y-vida-sin-drogas-devida",
        "adapter": "peru_intel.ingestion.devida",
        "official": 1, "kind": "oficial", "type": "xlsx",
        "license": "Datos abiertos del Estado peruano (PNDA)",
        "update_frequency": "anual", "geographic_level": "departamento",
        "coverage_start": "2018",
    },
    # ── Territorio ─────────────────────────────────────────────────────────
    {
        "source_id": "limites_inei",
        "name": "Límites departamentales, provinciales y distritales (simplificados)",
        "institution": "INEI (cartografía base) vía paquete OCE/FEDTID",
        "url": "https://www.inei.gob.pe/",
        "adapter": "peru_intel.map.territory",
        "official": 1, "kind": "oficial", "type": "geojson",
        "license": "Datos públicos del Estado peruano",
        "update_frequency": "eventual", "geographic_level": "departamento, provincia, distrito",
        "notes": "Polígonos provinciales generados aquí disolviendo distritos por UBIGEO (DuckDB spatial).",
    },
    {
        "source_id": "openfreemap",
        "name": "Mapa base vectorial OpenFreeMap (OpenStreetMap)",
        "institution": "OpenFreeMap · contribuidores de OpenStreetMap",
        "url": "https://openfreemap.org/",
        "adapter": "peru_intel.map.ofm_proxy",
        "official": 0, "kind": "vivo_tercero", "type": "tiles",
        "license": "ODbL (datos OSM) · estilos OpenMapTiles", "update_frequency": "semanal",
        "geographic_level": "calle",
    },
    # ── Infraestructura ────────────────────────────────────────────────────
    {
        "source_id": "apn_wpi_puertos",
        "name": "Puertos del Perú: carga (APN) + World Port Index (NGA)",
        "institution": "Autoridad Portuaria Nacional · NGA (EE. UU.)",
        "url": "https://piep.apn.gob.pe/datos-portuarios/",
        "adapter": "peru_intel.ingestion.ports",
        "official": 1, "kind": "oficial", "type": "xlsx/csv",
        "license": "Datos públicos", "update_frequency": "anual", "geographic_level": "puerto",
        "notes": "Pipeline build-international-data.mjs de OCE/FEDTID.",
    },
    {
        "source_id": "osm_datacenters",
        "name": "Centros de datos (telecom=data_center)",
        "institution": "OpenStreetMap vía RUC360",
        "url": "https://www.openstreetmap.org/",
        "adapter": "peru_intel.ingestion.ports",
        "official": 0, "kind": "vivo_tercero", "type": "json",
        "license": "ODbL", "update_frequency": "eventual", "geographic_level": "punto",
    },
    # ── En vivo ────────────────────────────────────────────────────────────
    {
        "source_id": "adsb_lol",
        "name": "Aeronaves ADS-B en vivo",
        "institution": "adsb.lol (red comunitaria) + adsbdb.com",
        "url": "https://api.adsb.lol/",
        "adapter": "peru_intel.live.adsb",
        "official": 0, "kind": "vivo_tercero", "type": "api",
        "license": "ODbL (adsb.lol)", "update_frequency": "~15 s", "geographic_level": "punto",
    },
    {
        "source_id": "aisstream",
        "name": "Embarcaciones AIS en vivo",
        "institution": "aisstream.io",
        "url": "https://aisstream.io/",
        "adapter": "peru_intel.live.ais",
        "official": 0, "kind": "vivo_tercero", "type": "websocket",
        "license": "Términos de aisstream.io", "update_frequency": "continuo", "geographic_level": "punto",
        "requires_key": "aisstream_key",
    },
    {
        "source_id": "celestrak",
        "name": "Elementos orbitales (GP/TLE)",
        "institution": "CelesTrak",
        "url": "https://celestrak.org/NORAD/elements/",
        "adapter": "peru_intel.live.celestrak",
        "official": 0, "kind": "vivo_tercero", "type": "api",
        "license": "Uso público con atribución", "update_frequency": "6 h", "geographic_level": "órbita",
    },
    {
        "source_id": "tomtom_traffic",
        "name": "Tráfico en vivo (flujo relativo)",
        "institution": "TomTom",
        "url": "https://developer.tomtom.com/traffic-api",
        "adapter": "peru_intel.live.traffic",
        "official": 0, "kind": "vivo_tercero", "type": "tiles/api",
        "license": "Términos comerciales TomTom (BYOK)", "update_frequency": "~1 min", "geographic_level": "tramo vial",
        "requires_key": "tomtom_key",
    },
    {
        "source_id": "igp_sismos",
        "name": "Sismos reportados",
        "institution": "Instituto Geofísico del Perú · CENSIS",
        "url": "https://ultimosismo.igp.gob.pe/",
        "adapter": "peru_intel.live.seismic",
        "official": 1, "kind": "oficial", "type": "api",
        "license": "Datos públicos IGP", "update_frequency": "minutos", "geographic_level": "epicentro",
    },
    {
        "source_id": "usgs_sismos",
        "name": "Sismos (fuente global secundaria)",
        "institution": "USGS Earthquake Hazards Program",
        "url": "https://earthquake.usgs.gov/earthquakes/feed/",
        "adapter": "peru_intel.live.seismic",
        "official": 1, "kind": "oficial", "type": "api",
        "license": "Dominio público (EE. UU.)", "update_frequency": "minutos", "geographic_level": "epicentro",
    },
    {
        "source_id": "nasa_firms",
        "name": "Focos de calor satelitales (VIIRS)",
        "institution": "NASA FIRMS",
        "url": "https://firms.modaps.eosdis.nasa.gov/",
        "adapter": "peru_intel.live.firms",
        "official": 1, "kind": "vivo_tercero", "type": "api",
        "license": "Datos abiertos NASA (MAP_KEY gratuita)", "update_frequency": "~3 h", "geographic_level": "píxel 375 m",
        "requires_key": "firms_key",
        "notes": "Un foco de calor satelital no es un incendio confirmado.",
    },
    {
        "source_id": "senamhi_estaciones",
        "name": "Observaciones de estaciones automáticas",
        "institution": "SENAMHI",
        "url": "https://www.senamhi.gob.pe/",
        "adapter": "peru_intel.live.weather",
        "official": 1, "kind": "oficial", "type": "csv",
        "license": "Datos públicos SENAMHI", "update_frequency": "horaria", "geographic_level": "estación",
        "requires_key": "senamhi_csv_url",
        "notes": "Requiere configurar la URL o el archivo del dataset de estaciones (ver DOCUMENTACION.md).",
    },
    {
        "source_id": "modelo_gfs",
        "name": "Pronóstico NOAA GFS (vía Open-Meteo)",
        "institution": "NOAA · servido por Open-Meteo",
        "url": "https://open-meteo.com/en/docs/gfs-api",
        "adapter": "peru_intel.live.weather",
        "official": 0, "kind": "proyeccion", "type": "api",
        "license": "CC BY 4.0 (Open-Meteo)", "update_frequency": "1 h", "geographic_level": "punto (capital departamental)",
    },
    {
        "source_id": "modelo_ecmwf",
        "name": "Pronóstico ECMWF IFS (vía Open-Meteo)",
        "institution": "ECMWF · servido por Open-Meteo",
        "url": "https://open-meteo.com/en/docs/ecmwf-api",
        "adapter": "peru_intel.live.weather",
        "official": 0, "kind": "proyeccion", "type": "api",
        "license": "CC BY 4.0 (Open-Meteo)", "update_frequency": "1 h", "geographic_level": "punto (capital departamental)",
    },
    # ── Derivados internos ─────────────────────────────────────────────────
    {
        "source_id": "indice_situacional_v1",
        "name": "Índice Situacional Perú v1 (experimental, no oficial)",
        "institution": "Cálculo propio · config/crime_index_v1.yaml",
        "url": "config/crime_index_v1.yaml",
        "adapter": "peru_intel.analytics.index",
        "official": 0, "kind": "calculado", "type": "derivado",
        "license": "Interno", "update_frequency": "al recalcular", "geographic_level": "departamento",
        "notes": "No es un índice oficial del MININTER ni de ninguna institución.",
    },
]

BY_ID = {s["source_id"]: s for s in SOURCES}
